### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by natenorberg** [paypal/downshift#304]
* `downshift` version: master (v1.23.2)
* `node` version: v6.10.1
* `npm` version: v5.6.0

What you did:
Forked and cloned the repo and ran `npm run setup`

What happened:

Got this error:
```
npm WARN eslint-import-resolver-babel-module@3.0.0 requires a peer of babel-plugin-module-resolver@^2.5.0 but none is installed. You must install peer dependencies yourself.

up to date in 11.816s
npm ERR! code ELIFECYCLE
npm ERR! errno 254
npm ERR! downshift@0.0.0-semantically-released setup: `npm install && npm run storybook:build -s && npm run validate`
npm ERR! Exit status 254
npm ERR!
npm ERR! Failed at the downshift@0.0.0-semantically-released setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It looks like the error happens in the `validate` script. When I run the scripts by hand, `install` and the storybook build pass, but `validate` throws this:

```
> downshift@0.0.0-semantically-released validate /Users/norberg/quiq/scratch/downshift
> kcd-scripts validate lint,build-and-test,test:cover,test:ts,test:ssr

/Users/norberg/quiq/scratch/downshift/node_modules/kcd-scripts/dist/utils.js:135
  scripts = Object.entries(scripts).reduce(function (all, _ref3) {
                   ^

TypeError: Object.entries is not a function
    at getConcurrentlyArgs (/Users/norberg/quiq/scratch/downshift/node_modules/kcd-scripts/dist/utils.js:135:20)
    at Object.<anonymous> (/Users/norberg/quiq/scratch/downshift/node_modules/kcd-scripts/dist/scripts/validate.js:32:53)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! downshift@0.0.0-semantically-released validate: `kcd-scripts validate lint,build-and-test,test:cover,test:ts,test:ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the downshift@0.0.0-semantically-released validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Reproduction repository:

https://github.com/natenorberg/downshift

I'm not sure if I'm doing something wrong here

**Comment by kentcdodds** [comment]
You need to be using version 8 of node. You're on version 6. I suggest using http://git.io/nvm

Good luck!

**Comment by austintackaberry** [comment]
I have this issue with node v8.9.4, 9.5.0, and 9.6.1 running `sudo npm run setup` 

However, I was able to get around it by individually running:

```
sudo npm install
sudo npm run storybook:install -s
sudo npm run storybook:build -s 
sudo npm run validate
```

**Comment by kentcdodds** [comment]
Hmmmm... That's pretty odd (and very dangerous) that you need to run those commands with `sudo`. Also super odd that it works when running them individually but not in a single command 🤔

**Comment by austintackaberry** [comment]
Ok thanks for the advice! I deleted every folder that required admin rights and ran `npm run setup` without any issues.
