### ISSUE TITLE
Incompatibility With StyledJSX in nextJS babel generator error

### ISSUE THREAD

**Issue by yuripramos** [paypal/downshift#349]
* `downshift` version: 1.28.1
* `node` version: 6.11.4
* `npm` (or `yarn`) version: 3.10.10

Hello Guys, I'm trying to implement the downshift as a component inside my application using nextJS. 
The issue is, when I use styledJSX I got this error:
```
Module build failed: TypeError: /mnt/c/projects/bppj-portal-frontend/components/AutoComplete/index.js: Cannot read property '0' of null
    at Buffer._append (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/buffer.js:95:25)
    at Buffer.append (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/buffer.js:72:10)
    at Generator._append (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:206:52)
    at Generator.word (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:131:10)
    at Generator.Identifier (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/generators/types.js:38:8)
    at /mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/buffer.js:168:5)
    at Generator.withSource (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.MemberExpression (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/generators/expressions.js:216:8)
    at /mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:298:23
    at Buffer.withSource (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/buffer.js:168:5)
    at Generator.withSource (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:189:15)
    at Generator.print (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:297:10)
    at Generator.AssignmentExpression (/mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/generators/expressions.js:190:8)
    at /mnt/c/projects/bppj-portal-frontend/node_modules/babel-generator/lib/printer.js:298:23
```
**My code:** 

```import { Fragment } from "react";
import Downshift from "downshift";
import Input from "../../components/ui/Input";
import { Search } from "../../components/icons";
import styles from "./styles";

export default function BasicAutocomplete({ items, onChange }) {
  return (
    <Fragment>
      <style jsx>{styles}</style>
      <Downshift
        onChange={onChange}
        render={({
          getItemProps,
          getInputProps,
          isOpen,
          inputValue,
          selectedItem,
          highlightedIndex
        }) => (
          <div>
            <Input
              name="AutoComplete"
              type="text"
              error
              placeholder="Digite o Nome"
              IconRight={() => <Search />}
              {...getInputProps({})}
            />
            {isOpen ? (
              <div className="test">
                {items
                  .filter(i => !inputValue || i.toLowerCase().includes(inputValue.toLowerCase()))
                  .map((item, index) => (
                    <div
                      {...getItemProps({ item })}
                      key={item}
                      style={{
                        backgroundColor: highlightedIndex === index ? "gray" : "white",
                        fontWeight: selectedItem === item ? "bold" : "normal"
                      }}
                    >
                      {item}
                    </div>
                  ))}
              </div>
            ) : null}
          </div>
        )}
      />
    </Fragment>
  );
}
```
The most bizarre situation is when I comment or delete the `{...getItemProps({ item })}`  OR `<style jsx>{styles}</style>` everything works fine, I'm trying to catch whats wrong, looking forward the docs but still no results.

**Comment by madox2** [comment]
@yuripramos did you manage to resolve this issue?

**Comment by KamWis** [comment]
The reason for that behaviour is `spread operator`. For some reason, if it's present in markup, it will crash with above error. Like in mine case:

If I do:
```
<span { ...{ 'xmlns:v': 'http://rdf.data-vocabulary.org/#' }}>
    <a rel="v:url" href="/foo">Foo</a> &gt; <a rel="v:url" href="/foo/bar">Bar</a> &gt; <a rel="v:url" href="/foo/bar/baz">Baz</a>
  </span>
```
It will crash.

If I extract it like that:

```
const XmlnsSpan = (props) => (
  <span { ...{ 'xmlns:v': 'http://rdf.data-vocabulary.org/#' }}>
    {props.children}
  </span>
);
```

and use it in the markup there the styles are:
```
<XmlnsSpan>
  <a rel="v:url" href="/foo">Foo</a> &gt; <a rel="v:url" href="/foo/bar">Bar</a> &gt; <a rel="v:url" href="/foo/bar/baz">Baz</a>
</XmlnsSpan>
```

It will be just fine

**Comment by solomonakp** [comment]
@pencilcheck  @yuripramos 
were you able to use this for server side on rendering on next.js and was the issue fixed ??
