### ISSUE TITLE
Contributor workflow: test failures relating to React Native

### ISSUE THREAD

**Issue by dallonf** [paypal/downshift#567]
- `downshift` version: master branch (commit `784c4b9dc4deed3286c9552bf9126ce4e0ffb9e6`)
- `node` version: v8.11.3
- `npm` (or `yarn`) version: npm 5.6.0
- OS version: macOS High Sierra 10.12.6 (16G1510)

**Relevant code or config**

N/A

**What you did**:

Made a fork of the project, cloned locally, ran `npm run setup` as recommended by `CONTRIBUTING.md`

**What happened**:

~~The command failed, seemingly on a Flow error of some sort:~~

```
[test:flow:coverage] Error while generating Flow Coverage Report: Error: Command failed: flow status --json
[test:flow:coverage]
[test:flow:coverage] Out of retries, exiting!
[test:flow:coverage]  Error: Command failed: flow status --json
[test:flow:coverage]
[test:flow:coverage] Out of retries, exiting!
[test:flow:coverage]
[test:flow:coverage]     at ChildProcess.exithandler (child_process.js:275:12)
[test:flow:coverage]     at emitTwo (events.js:126:13)
[test:flow:coverage]     at ChildProcess.emit (events.js:214:7)
[test:flow:coverage]     at maybeClose (internal/child_process.js:925:16)
[test:flow:coverage]     at Socket.stream.socket.on (internal/child_process.js:346:11)
[test:flow:coverage]     at emitOne (events.js:116:13)
[test:flow:coverage]     at Socket.emit (events.js:211:7)
[test:flow:coverage]     at Pipe._handle.close [as _onclose] (net.js:557:12)
```

[full log: 2018-08-29T18_58_47_524Z-debug.log](https://github.com/paypal/downshift/files/2333571/2018-08-29T18_58_47_524Z-debug.log)

~~Unfortunately I haven't done much with Flow, so I don't know what might be causing this or how to fix it.~~

Earlier, I was getting some test failures that seemed to be related to React Native - but I'm also not experienced enough with React Native to try to troubleshoot. ~~In any case, I can't reproduce that failure anymore, it's the Flow error now. I'll try rebooting in a moment to see if it's _that_ sort of problem.~~

**Update:** It was indeed _that_ sort of problem. I can reproduce the React Native test failures now! The Flow error probably has more to do with Flow just being generally unstable in my experience than this project.

Here are the test failures:

```
[build-and-test]  FAIL  other/react-native/__tests__/render-tests.js
[build-and-test]   ● Console
[build-and-test]
[build-and-test]     console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
[build-and-test]       The above error occurred in the <Downshift> component:
[build-and-test]           in Downshift
[build-and-test]
[build-and-test]       Consider adding an error boundary to your tree to customize error handling behavior.
[build-and-test]       Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
[build-and-test]     console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
[build-and-test]       The above error occurred in the <Downshift> component:
[build-and-test]           in Downshift
[build-and-test]
[build-and-test]       Consider adding an error boundary to your tree to customize error handling behavior.
[build-and-test]       Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
[build-and-test]
[build-and-test]   ● renders with React Native components
[build-and-test]
[build-and-test]     Jest encountered an unexpected token
[build-and-test]
[build-and-test]     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
[build-and-test]
[build-and-test]     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
[build-and-test]
[build-and-test]     Here's what you can do:
[build-and-test]      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
[build-and-test]      • If you need a custom transformation specify a "transform" option in your config.
[build-and-test]      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
[build-and-test]
[build-and-test]     You'll find more details and examples of these config options in the docs:
[build-and-test]     https://jestjs.io/docs/en/configuration.html
[build-and-test]
[build-and-test]     Details:
[build-and-test]
[build-and-test]     /Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Components/TextInput/TextInput.js:15
[build-and-test]     const if (process.env.NODE_ENV !== "production") {
[build-and-test]           ^^
[build-and-test]
[build-and-test]     SyntaxError: Unexpected token if
[build-and-test]
[build-and-test]       11 |   const childrenSpy = jest.fn(({getRootProps, getInputProps, getItemProps}) => (
[build-and-test]       12 |     <RootView {...getRootProps({refKey: 'innerRef'})}>
[build-and-test]     > 13 |       <TextInput {...getInputProps()} />
[build-and-test]          |        ^
[build-and-test]       14 |       <View>
[build-and-test]       15 |         <Text {...getItemProps({item: 'foo', index: 0})}>foo</Text>
[build-and-test]       16 |         <Text {...getItemProps({item: 'bar', index: 1})}>bar</Text>
[build-and-test]
[build-and-test]       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
[build-and-test]       at requireActual (node_modules/react-native/jest/mockComponent.js:10:33)
[build-and-test]       at Object.mockComponent [as user:/Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Components/TextInput/TextInput.js:] (node_modules/react-native/jest/setup.js:38:28)
[build-and-test]       at Object.require [as TextInput] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:51:28)
[build-and-test]       at other/react-native/__tests__/render-tests.js:13:8
[build-and-test]
[build-and-test]   ● can use children instead of render prop
[build-and-test]
[build-and-test]     TypeError: Class extends value [object Object] is not a constructor or null
[build-and-test]
[build-and-test]       36 |   const childrenSpy = jest.fn(({getRootProps, getInputProps, getItemProps}) => (
[build-and-test]       37 |     <RootView {...getRootProps({refKey: 'innerRef'})}>
[build-and-test]     > 38 |       <TextInput {...getInputProps()} />
[build-and-test]          |        ^
[build-and-test]       39 |       <View>
[build-and-test]       40 |         <Text {...getItemProps({item: 'foo', index: 0})}>foo</Text>
[build-and-test]       41 |         <Text {...getItemProps({item: 'bar', index: 1})}>bar</Text>
[build-and-test]
[build-and-test]       at RealComponent (node_modules/react-native/jest/mockComponent.js:13:35)
[build-and-test]       at Object.mockComponent [as user:/Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Components/TextInput/TextInput.js:] (node_modules/react-native/jest/setup.js:38:28)
[build-and-test]       at Object.require [as TextInput] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:51:28)
[build-and-test]       at other/react-native/__tests__/render-tests.js:38:8
[build-and-test]       at Downshift.children [as render] (dist/downshift.native.cjs.js:721:31)
[build-and-test]
[build-and-test]  FAIL  other/react-native/__tests__/onChange-tests.js (7.129s)
[build-and-test]   ● Console
[build-and-test]
[build-and-test]     console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
[build-and-test]       The above error occurred in the <Downshift> component:
[build-and-test]           in Downshift
[build-and-test]
[build-and-test]       Consider adding an error boundary to your tree to customize error handling behavior.
[build-and-test]       Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
[build-and-test]     console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
[build-and-test]       The above error occurred in the <Downshift> component:
[build-and-test]           in Downshift
[build-and-test]
[build-and-test]       Consider adding an error boundary to your tree to customize error handling behavior.
[build-and-test]       Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
[build-and-test]
[build-and-test]   ● calls onChange when TextInput changes values
[build-and-test]
[build-and-test]     Jest encountered an unexpected token
[build-and-test]
[build-and-test]     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
[build-and-test]
[build-and-test]     By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".
[build-and-test]
[build-and-test]     Here's what you can do:
[build-and-test]      • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
[build-and-test]      • If you need a custom transformation specify a "transform" option in your config.
[build-and-test]      • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
[build-and-test]
[build-and-test]     You'll find more details and examples of these config options in the docs:
[build-and-test]     https://jestjs.io/docs/en/configuration.html
[build-and-test]
[build-and-test]     Details:
[build-and-test]
[build-and-test]     /Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Text/Text.js:18
[build-and-test]     const if (process.env.NODE_ENV !== "production") {
[build-and-test]           ^^
[build-and-test]
[build-and-test]     SyntaxError: Unexpected token if
[build-and-test]
[build-and-test]       19 |           <Input {...getInputProps({onChange})} />
[build-and-test]       20 |           <View>
[build-and-test]     > 21 |             <Text {...getItemProps({item: 'foo', index: 0})}>foo</Text>
[build-and-test]          |              ^
[build-and-test]       22 |             <Text {...getItemProps({item: 'bar', index: 1})}>bar</Text>
[build-and-test]       23 |           </View>
[build-and-test]       24 |         </RootView>
[build-and-test]
[build-and-test]       at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
[build-and-test]       at requireActual (node_modules/react-native/jest/mockComponent.js:10:33)
[build-and-test]       at Object.mockComponent [as user:/Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Text/Text.js:] (node_modules/react-native/jest/setup.js:37:23)
[build-and-test]       at Object.require [as Text] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:50:23)
[build-and-test]       at other/react-native/__tests__/onChange-tests.js:21:14
[build-and-test]
[build-and-test]   ● calls onChangeText when TextInput changes values
[build-and-test]
[build-and-test]     TypeError: Class extends value [object Object] is not a constructor or null
[build-and-test]
[build-and-test]       49 |           <Input {...getInputProps({onChangeText})} />
[build-and-test]       50 |           <View>
[build-and-test]     > 51 |             <Text {...getItemProps({item: 'foo', index: 0})}>foo</Text>
[build-and-test]          |              ^
[build-and-test]       52 |             <Text {...getItemProps({item: 'bar', index: 1})}>bar</Text>
[build-and-test]       53 |           </View>
[build-and-test]       54 |         </RootView>
[build-and-test]
[build-and-test]       at RealComponent (node_modules/react-native/jest/mockComponent.js:13:35)
[build-and-test]       at Object.mockComponent [as user:/Users/dallonfeldner/devroot/oss/downshift/node_modules/react-native/Libraries/Text/Text.js:] (node_modules/react-native/jest/setup.js:37:23)
[build-and-test]       at Object.require [as Text] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:50:23)
[build-and-test]       at other/react-native/__tests__/onChange-tests.js:51:14
[build-and-test]       at Downshift.children [as render] (dist/downshift.native.cjs.js:721:31)
[build-and-test]       at render (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5276:31)
[build-and-test]       at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5238:10)
[build-and-test]       at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5907:14)
[build-and-test]
[build-and-test] Test Suites: 2 failed, 2 passed, 4 total
[build-and-test] Tests:       4 failed, 5 passed, 9 total
[build-and-test] Snapshots:   0 total
[build-and-test] Time:        9.198s
[build-and-test] Ran all test suites in 2 projects.
```

[full log: 2018-08-29T20_09_18_416Z-debug.log](https://github.com/paypal/downshift/files/2333652/2018-08-29T20_09_18_416Z-debug.log)

**Reproduction repository**:

This one 😛 

**Problem description**:

Contributor instructions on a fresh clone fail with confusing errors.

**Suggested solution**:

Regularly test the project setup process so new contributors don't get tripped up! (alternatively, if it's an environment issue, document any prerequisites or assumptions made by the workflow scripts)

**Comment by kentcdodds** [comment]
Yeah, we're aware of the react native issues. I'm not sure what's going on with flow for you. I'm afraid that I don't have time to figure out what's going on, but if you have some time (or anyone else) to do some digging that would be really helpful.

**Comment by dallonf** [comment]
After a quick reboot, the Flow errors went away... which I should have tried earlier, Flow has never been particularly stable in my local environment. Now we've at least got a ticket for the React Native test failure, I guess!

**Comment by kentcdodds** [comment]
Yes, thank you for that.

I've had trouble with flow reliability on my machine as well. It's pretty frustrating to be honest :-(
